Bla 66 emoji client
frontandrew/black-jack pull request #136
Opened 2024-09-01 20:19 UTC by TentakleM1

### Какую задачу решаем
Сделал эмоции на клиенте на посты и коменты 

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-09-02 18:13 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +      <Popper id={idEmoji} open={open} anchorEl={anchorEl}>
Панелька с выбором эмоджи должна автоматически скрываться при клике за ее пределами. Как следствие не должно возникать ситуации, когда одновременно открыты 2 или больее панельки.

![image](https://github.com/user-attachments/assets/db5b3d44-fec7-4790-bdb9-0cca4648dd5a)

2024-09-02 18:14 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +      <Popper id={idEmoji} open={open} anchorEl={anchorEl}>
Так же панелька должна скрываться по клику по уже активнону (выбранному) emoji.

![image](https://github.com/user-attachments/assets/fa04ccca-57b6-4190-a207-2d9ddcb3a598)

2024-09-02 18:18 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +      <Popper id={idEmoji} open={open} anchorEl={anchorEl}>
В целом компонент Popper предназначен для других задач. Тут следует использовать компонент Popover.

2024-09-02 18:24 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +  const emojiPack = ['😀', '🧐', '🤮', '😑', '🤬', '😁', '😌', '👆', '👇']
`emojiPack` выглядит как константа или конфигурация. Стоит вынести в общий переиспользуемый код.

2024-09-02 18:27 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +export const EmojiChoice: FC = () => {
Проблему с версткой нужно решить.

![image](https://github.com/user-attachments/assets/265f901f-151d-4f7a-b401-53739823e634)

2024-09-02 18:33 UTC, frontandrew requested changes

2024-09-02 18:33 UTC, frontandrew commented on packages/client/src/pages/forum/topic/view.tsx
При взаимодействии с эможди верстка страницы не должна прыгать.

![firefox_qt5uvucB4F](https://github.com/user-attachments/assets/8bfd69cf-200b-455a-835f-83e7d3d02400)

2024-09-03 14:17 UTC, TentakleM1 commented on packages/client/src/pages/forum/emoji/view.tsx
> +      // @ts-ignore
смайл это стринг, но не пропускает проверки, вот такое вот нашел: https://github.com/anthonyyangdev/emoji-type

2024-09-03 14:19 UTC, TentakleM1 commented on packages/client/src/pages/forum/emoji/view.tsx
> +      // @ts-ignore
вроде прошли проверки

2024-09-03 17:27 UTC, frontandrew requested changes

2024-09-03 17:27 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +        <Box
Чернаую обводку вокруг панельки нужно убрать. 
![image](https://github.com/user-attachments/assets/63a7d838-7d9d-4ca9-9275-ae10821fe5b7)

2024-09-03 18:50 UTC, TentakleM1 commented on packages/client/src/pages/forum/emoji/view.tsx
> +        <Box
![image](https://github.com/user-attachments/assets/7564299e-98ca-47db-90bf-e0b833a3a010)

done

2024-09-03 18:50 UTC, TentakleM1 commented on packages/client/src/pages/forum/emoji/view.tsx
> +      // @ts-ignore
<string[]> такой тип указал

2024-09-04 00:45 UTC, frontandrew requested changes
Есть замечания

2024-09-04 00:45 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +            </Box>
Чилсло отметок не растягивает контейнер. Исправить.
![firefox_Kx6uArmRax](https://github.com/user-attachments/assets/121e5167-0457-4060-9c0a-8afde8430efb)

2024-09-04 00:45 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +        <Box maxWidth={70} display={'flex'} alignItems={'center'}></Box>
Зачем нужен этот компонент?

2024-09-04 00:45 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +              </Typography>
Число отметок должно быть выравнено по чентру контейнера. Исправить.
![firefox_Kx6uArmRax](https://github.com/user-attachments/assets/121e5167-0457-4060-9c0a-8afde8430efb)

2024-09-04 00:45 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +              </Typography>
Цвает шрибта стоит поменять на белый.

2024-09-04 00:45 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +            <Box
В качестве контейнера для отметок стоит использовать компонент Chip

2024-09-04 00:45 UTC, frontandrew commented on packages/client/src/pages/forum/emoji/view.tsx
> +              </IconButton>
Не нравится что эмоджи как будто полу прозрачные, вглядит странно. Почему так?

2024-09-04 10:18 UTC, TentakleM1 commented on packages/client/src/pages/forum/emoji/view.tsx
> +              </Typography>
![Снимок экрана 2024-09-04 131516](https://github.com/user-attachments/assets/04e60eb1-9e63-4fe8-bcbb-1c2026eeaec7)
![Снимок экрана 2024-09-04 131504](https://github.com/user-attachments/assets/ae6ede1f-0896-40e4-9127-df9f2db2f9de)

Поправил

2024-09-04 10:19 UTC, TentakleM1 commented on packages/client/src/pages/forum/emoji/view.tsx
> +        <Box maxWidth={70} display={'flex'} alignItems={'center'}></Box>
что бы верстка не скакал, хотя я уже поправил, и там пустышка

2024-09-04 10:20 UTC, TentakleM1 commented on packages/client/src/pages/forum/emoji/view.tsx
> +              </Typography>
поменял дизайн 
![Снимок экрана 2024-09-04 131446](https://github.com/user-attachments/assets/07ac399a-3730-4bd4-a8d6-03b410cffd67)

2024-09-04 10:20 UTC, TentakleM1 commented on packages/client/src/pages/forum/emoji/view.tsx
> +              </IconButton>
Сам до сих пор не понял почему, но щас не прозрачные

2024-09-04 10:21 UTC, TentakleM1 commented on packages/client/src/pages/forum/emoji/view.tsx
> +            </Box>
![Снимок экрана 2024-09-04 131516](https://github.com/user-attachments/assets/57048199-6f3a-489c-a1d7-c8da890cf82e)
терь растягивает

2024-09-04 22:20 UTC, frontandrew approved these changes

2024-09-05 05:32 UTC, kyzinatra approved these changes
Отличная работа! Отдельно отмечу хорошее ревью ваших коллег. Понравилась верстка и типизация проекта. Вопросов по реализации эмоджи у меня нет. Вы отлично потрудились!

2024-09-05 12:12 UTC, merged