Bla 20 errorpage
frontandrew/black-jack pull request #38
Opened 2024-06-25 06:57 UTC by TentakleM1

### Какую задачу решаем

изменил роутинг, хук useRouteError работает только в  RouterProvider, поэтому создал маршрутизатор createBrowserRouter, и обернул в RouterProvider, от этого сильно ничего не поменялось, теперь проще отлавливать ошибки, также сделана страница error page

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-06-25 07:53 UTC, Ratanov requested changes

2024-06-25 07:53 UTC, Ratanov commented on packages/client/src/app/view.tsx
> +
Нужно вынести в отдельный файл, напр. router.ts и подключить к view.tsx. 
PS расширение .tsx используем только, где есть React и его разметка. В остальных случаях .ts

2024-06-25 07:53 UTC, Ratanov commented on packages/client/src/app/view.tsx
> +
сам router.ts положить рядом

2024-06-25 11:02 UTC, Ratanov approved these changes

2024-06-26 07:05 UTC, frontandrew requested changes
- использовать типизированные компоненты
- внести роутеы из app

2024-07-01 12:56 UTC, frontandrew requested changes

2024-07-01 12:56 UTC, frontandrew commented on packages/client/src/app/view.tsx
>    }, [])
Не понятно зачем оставлен пустой хук? В этом есть смысл? Если нет - удалить.

2024-07-01 13:16 UTC, TentakleM1 commented on packages/client/src/app/view.tsx
>    }, [])
Ты про useEffect, так он же с самого начала там ?

2024-07-01 13:42 UTC, frontandrew commented on packages/client/src/app/view.tsx
>    }, [])
Да

2024-07-16 13:12 UTC, closed without merging