feat: BLA-32 страница начала игры, BLA-36 механика игры, BLA-43 страница завершения игры
frontandrew/black-jack pull request #39
Opened 2024-06-27 08:45 UTC by Ratanov

### Какую задачу решаем
BLA-32 - страница начала игры '/start'
BLA-36 - механика игры
BLA-43 - страница завершения игры  '/finish'

Покрыл код комментариями для понимания логики работы

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-06-27 11:56 UTC, frontandrew requested changes
Отличная работа! Здорово что игровая механика вынесена в отдельную фичу. Круто, что реализован алгоритм для перемешивания карт. Код отлично документирован.

1. Непонимание вызывает структура игры, на мой взгляд она переусложнена ненужными вложениями, и порой даже вводит в заблуждение (например, `gameSlice.ts` расположен в папке /ui, хотя не является представлением).

Очевидно, что `features/gameCanvas` и `features/gameSlice` это две части одной фичи. 

`features/gameCanvas` - это представление игры
`features/gameSlice` - это модель данных игры

По логике FSD структура могла бы выглядеть так:
```
/features
   /game
        model.ts - логика игры gameSlice.ts
        view.tsx - представление игры gameCanvas.tsx
        type.ts - типы 
        index.ts
 ```

Схожая ситуация на уровне `pages`.

Нет ни какого смысла называть файлы внутри папки тем же именем что и папка, это создает визуальный шум и подталкивает придумывать все новые и новые комбинации в названиях файлов. Как пример `gameSlice.types.ts` - здесь ты вынужден был добавить постфикс `types`, чтобы явно сказать что этот файл содержит типы и не дублировать имя `gameSlice.ts` из соседней папки.

FSD предписывает именовать файлы в соответствии с их ролью в составе слайса.

Допустим не пишем .jsx, а используем шаблоны. Как догда именовать файлы для страницы? Попробуем представить, что в фиче `game` нужны еще специфичные утилиты (например для перемешивания карт или еще чего-то), наверное получится что-то вроде:

```
/features
   /game
        game.ts
        game.type.ts
        /ui
             game.tmpl
             game.css
        /utils
             game.cardshuffle.ts
             game.createDeck.ts
        index.ts
```

Функии выполняемые каждым файлом, вроде как понятны по расширению. Но вот, опять же game.ts - явно не говорит о своей роли. Можно конечно добавить ему постфикс `.model.ts`, уже лучше:

```
/features
   /game
        game.model.ts
        game.type.ts
        /ui
             game.tmpl
             game.css
        /utils
             game.cardshuffle.ts
             game.createDeck.ts
        index.ts
```

В итоге, имена файлов содержат префикс game, как бы показывая свою принадлежность, хотя принадлежность их очевидна по их расположению - они принадлежат фиче `game`. Так зачем об этом лишний раз напоминать, это избыточность и лишний шум.

Давайте окинем лишнее и назовем файлы в соответствии с их ролью:

```
/features
   /game
        model.ts
        type.ts
        view.tmpl
        style.css
        /utils
             cards-huffle.ts
             create-deck.ts
        index.ts
```

На мой взгляд стало гораздо проще воспринимать. Файлы именованы в едином ключе. Ни у кого не должно возникнуть вопросов, какой файл за что отвечает.

Ну и - краткость - сестра таланта, конечно))

2. Предлагаю все тексты в UI писать на английском языке. Так уже делают 2 из 3 членов команды.

**UPD:**

3. Как будто `/utils/card` не будут использованы ни где, кроме фичи `game`. Если это так, предлагаю расположить их по месту использования. Можно разделить как в примере выше, оставить в одном файле аля `utils.ts`.

2024-06-27 12:01 UTC, Ratanov commented
оки Андрей, поправлю

2024-06-27 22:45 UTC, frontandrew approved these changes
Все отлично, замечаний нет.

2024-06-28 10:50 UTC, DazzlingFame approved these changes
Привет, хорошая работа! Вижу, что часть комментариев ты поправил ещё в процессе ревью с командой, это очень круто!
В текущем состоянии работы не заметил критичных замечаний, так что работу принимаю 👍

Очень классно, что используешь типизацию `FC` в React компонентах и оставляешь поясняющие комментарии в коде, это полезные практики 👍

2024-07-01 06:58 UTC, merged