Bla 33 integrate validation
frontandrew/black-jack pull request #76
Opened 2024-07-16 13:14 UTC by TentakleM1

### Какую задачу решаем
Интегрировал валидатор в форму пользователя, логин, и регистрации 

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-07-16 14:19 UTC, frontandrew requested changes
Можно лучше.

2024-07-16 14:19 UTC, frontandrew commented on packages/client/src/pages/settings/components/form-user/view.tsx
> +import { phone } from '../../../../shared/validation/validators/phone/phone'
Так е нада. Нада адин путь сделать и все валидаторы доставать из этого пути. Везде, где валидатор используется, конечно же.

2024-07-16 14:23 UTC, frontandrew requested changes

2024-07-16 19:39 UTC, TentakleM1 commented on packages/client/src/pages/reg/view.tsx
> +import { phone } from '../../shared/validation/validators/phone/phone'
глобальный импорт чек

2024-07-16 20:56 UTC, Ratanov commented on packages/client/src/shared/validation/validators/email/email.ts
>    if (value === undefined) {
Не отправляем пустую строку в ошибку. Также можно еще на null проверить

if (value === undefined || value === null) {
    errors.push('Email is required.');
    return errors[0]
 }

возвращать errors[0] тоже не очень правильно. нужно отправлять весь массив ошибок, а уже где принимаешь перебирать

2024-07-16 20:56 UTC, Ratanov commented on packages/client/src/pages/login/view.tsx
>  import './style.css'
импорты нужно писать правильно, без пустых строк. Самые менее важные файлы, такие как стили и компоненты дизайн системы, писать в конце.

**Вот рекомендуемый порядок импортов:**
1. Сначала импортируй встроенные модули Node.js (если есть, у тебя их нет):
```
import path from 'path';
import fs from 'fs';
```

2. Затем React и связанные с ним импорты
```
import React from 'react';
import { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
```

3. Внешние зависимости и UI компоненты:
```
import { Box, Button, Grid, Paper, Typography, useTheme } from '@mui/material';
import axios from 'axios';
```

4. После этого компоненты из других файлов:
```
import Header from './components/Header';
import Footer from './components/Footer';
```

5. Далее импортируются утилиты, хуки и другие вспомогательные функции:
```
import { formatDate } from '../utils/dateUtils';
import useCustomHook from '../hooks/useCustomHook';
```

6. В конце импортируются стили и ресурсы:
```
import styles from './style.css';
import logo from '../assets/logo.png';
```

**В твоем случае было бы так:**
import { FC } from 'react'  (это вообще не нужно, если использовать в коде React.FC вместо FC)
import { useNavigate } from 'react-router'
import { Box, Button, Grid, Paper, Typography, useTheme } from '@mui/material'
import { useForm } from 'react-final-form-hooks'
import { FieldText } from 'components'
import { validators } from 'validators'
import './style.css'

2024-07-16 20:56 UTC, Ratanov commented on packages/client/src/pages/login/view.tsx
>  export const LoginPage: FC = () => {
вместе FC лучше писать React.FC (убери после исправления import { FC } from 'react')

2024-07-17 01:07 UTC, Ratanov approved these changes

2024-07-17 05:27 UTC, kyzinatra commented on packages/client/src/shared/validation/validators/email/email.ts
> +  }
Стоит указать, что именно вы считаете корректным именем. То есть Какие условия такого имени

2024-07-17 05:27 UTC, kyzinatra commented on packages/client/src/shared/validation/validators/login/login.ts
>    if (/^[0-9]+$/.test(value)) {
Хорошая валидация логина

2024-07-17 05:28 UTC, kyzinatra commented on packages/client/src/shared/validation/validators/login/login.ts
>    }
Я бы вынес валидаторы вообще в отдельный пакет, так как они понадобятся и на `backend` части, ведь валидировать данные обязательно нужно и там и там

2024-07-17 05:33 UTC, kyzinatra approved these changes
Отличная реализация валидаторов. Я бы посоветовал вынести их в отдельный пакет, чтобы использовать везде. lerna это позволяет делать. В остальном мне все понравилось. Хорошее использование и реализация! Ваша работа принята, продолжайте в том же духе! Будем и дальше ждать от вас работ на проверку

2024-07-17 08:48 UTC, frontandrew approved these changes

2024-07-17 10:06 UTC, frontandrew requested changes

2024-07-17 10:06 UTC, frontandrew commented on package.json
>    }
Опять эти зависимости. Кто-то может их удалить?

2024-07-17 14:38 UTC, closed without merging