Bla 49 service worker
frontandrew/black-jack pull request #77
Opened 2024-07-16 20:32 UTC by TentakleM1

### Какую задачу решаем
Сделал модуль SW, при отсутствия интернета игра работает 

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-07-17 03:01 UTC, Ratanov approved these changes
approved

2024-07-17 07:06 UTC, frontandrew requested changes
Опять в задаче по сервис воркеру 100500 других задач.

2024-07-17 07:06 UTC, frontandrew commented on package.json
>    }
Откуда это? Нельзя пользоваться `NPM`.

2024-07-17 08:36 UTC, TentakleM1 commented on package.json
>    }
Были проблемы с тестами, пришлось поставить

2024-07-18 01:32 UTC, kyzinatra commented on packages/client/public/sw.js
> +    caches.match(event.request).then(response => {
Хорошо сделан fetch

2024-07-18 01:35 UTC, kyzinatra commented on packages/client/public/sw.js
> +  'start',
Надо исправить: сервис воркер не знает что именно тут нужно кэшировать. У вас же SPA, так что вам не нужно кэшировать одну и ту же страницу 10 раз. Достаточно только 1 раз `index.html` файл зарегестрировать. Также тут не указаны css и js файлы. Воркер сам их найти не сможет, то же касается картинок. Стоит сделать скрипт или использовать библиотеку вроде workbox которая найдиет и впишет нужные пути до всех файлов

2024-07-18 01:36 UTC, kyzinatra requested changes
Отличная работа! Понравилось, как вы реализовали кэширование fetch, но сервис воркер не знает что именно нужно кэшировать в URLS. У вас же SPA, так что вам не нужно кэшировать одну и ту же страницу 10 раз. Достаточно только 1 раз `index.html` файл зарегестрировать. Также тут не указаны css и js файлы. Воркер сам их найти не сможет, то же касается картинок. Стоит сделать скрипт или использовать библиотеку вроде workbox которая найдиет и впишет нужные пути до всех файлов

2024-07-18 05:04 UTC, TentakleM1 commented on packages/client/public/sw.js
> +  'start',
Он вроде все кэширует 

![Снимок экрана 2024-07-18 080316](https://github.com/user-attachments/assets/a1d2f133-1538-4968-822c-77282997910b)
![Снимок экрана 2024-07-18 074252](https://github.com/user-attachments/assets/55fc061d-f4d5-4c2c-b8a1-5946f4416ae1)

2024-07-18 05:16 UTC, kyzinatra commented on packages/client/public/sw.js
> +  'start',
Странно, у меня не кэшировало. Возможно этот кэш из-за настроек феча. Я чуть позже днем еще раз запущу и напишу почему так происходит

2024-07-18 14:30 UTC, kyzinatra commented on packages/client/public/sw.js
> +  'start',
По всей видимости файлы, которые вы видите кэшируются не on sw install, а с помощью обработчика fetch. Попробуйте его убрать и вы увидите то, что на скриншоте. Это не очень хорошо, так как появляется много проблем с инвалиацией кэша. Не стоит так кэшировать статику. Впрочем, и так работать в теории будет, так что если вы просто уберете все и оставите только кэширование fetch, то я это пропущу, но все равно вы должны знать, что это не хорошо. 
Сейчас же стоит убрать, а лучше переделать не рабочий код и добавить всю статику в него.

![image](https://github.com/user-attachments/assets/74ec116b-c70f-43f3-a23c-ed2d66e1a0d6)

2024-08-16 10:03 UTC, closed without merging