Bla 30 29 changes
frontandrew/black-jack pull request #81
Opened 2024-07-20 08:13 UTC by TentakleM1

### Какую задачу решаем
Создал модальное окно для смены пароля, и аватара, сразу интегрировал валидатор в для пароля, для вызова модального окна по смене пароля добавил кнопку в settings page.

### Скриншоты/видяшка (если есть)

![Снимок экрана 2024-07-20 110913](https://github.com/user-attachments/assets/0650eba3-4fb4-4a5c-b126-fee1a4eedd92)
![Снимок экрана 2024-07-20 110922](https://github.com/user-attachments/assets/b77e2cbb-9d3a-401f-bc2d-d945a82cf393)

### TBD (если есть)

2024-07-21 08:57 UTC, frontandrew requested changes
Не плохо. Есть моменты:
[ ] - верстка
[ ] - подтверждение  пароля
[ ] - нэйминг компонента не понятный
[ ] - смешивание ответственности

2024-07-21 08:57 UTC, frontandrew commented on packages/client/src/pages/settings/components/card-user/view.tsx
> +        </Button>
Тут очевидно не влезает новая кнопка. 3 большие кнопки ломают макет, так нельзя.

![image](https://github.com/user-attachments/assets/369a1f20-04df-40cd-b534-bcadffbee491)

Организуй кнопки иначе, не ломая макет.

2024-07-21 08:57 UTC, frontandrew commented on packages/client/src/pages/settings/components/card-user/components/changes/view.tsx
> +}
У этого компонента 2 ответственности:
- изменять пароль
- изменять аватар

Так делать не следует, это классическая "лапша". Верно будет разделить на 2 формы и дать модулям понятные имена.

2024-07-21 08:57 UTC, frontandrew commented on packages/client/src/pages/settings/view.tsx
> -        <Grid item padding={spacing(4, 8)} minWidth={400}>
Макетом заложен отступ в 8 единиц.

2024-07-21 08:57 UTC, frontandrew commented on packages/client/src/pages/settings/components/card-user/components/changes/view.tsx
> +          />
Не понятно почему в форме нет проверки на совпадение пароля.

2024-07-21 14:48 UTC, TentakleM1 commented on packages/client/src/pages/settings/view.tsx
> -        <Grid item padding={spacing(4, 8)} minWidth={400}>
Так я этого и не писал, это ты делал разметку профиля, мне просто 8у убрать ?
![Снимок экрана 2024-07-21 174800](https://github.com/user-attachments/assets/f998a191-f073-4f84-9c82-bbd052874b28)

2024-07-21 14:50 UTC, TentakleM1 commented on packages/client/src/pages/settings/components/card-user/components/changes/view.tsx
> +          />
Немного не понял этого момента ?
Как это реализовать, где храниться сам пароль ?

2024-07-22 12:45 UTC, frontandrew commented on packages/client/src/pages/settings/view.tsx
> -        <Grid item padding={spacing(4, 8)} minWidth={400}>
Возможно я ошибся. Я подумал что это место где изменился отступ на маленький. Я про эту проблему:

2024-07-22 12:48 UTC, frontandrew commented on packages/client/src/pages/settings/components/card-user/components/changes/view.tsx
> +          />
Ты должен заставить пользака ввести пароль 2 раза одинаковый вслепую. Тем самым мы убедимся что челик эго немножко помнит.

2024-07-22 13:10 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +type Password = object
что еще за тип object? Разве нас так учили писать?

```
interface Password {
  password: string;
}
```

2024-07-22 13:10 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +const config = {
лучше тогда переменную назвать formConfig
console.table и все прочие консоли в пулл реквесте (в итоговой версии) быть НЕ должо
все консольлоги нужны только тебе при отладке

2024-07-22 13:10 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +  const { isOpen, handle } = props
завел две лишние переменные. если тебе нужны пропсы, сразу укажи их при создании компонента: 
`export const ChangePasswordModal: React.FC<PropsChange> = ({ isOpen, handle }) => {`

2024-07-22 13:10 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +        onSubmit: (event: React.FormEvent<HTMLFormElement>) => {
писать в разметке код - моветон. лучше вынести в отдельную функцию, пусть даже это будет одна строка.
Все что у нас в return - это разметка и функции, которые вызываем. Описание функций в разметке делать НЕ нужно
```
const onSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    handleSubmit();
  };

return (
<Dialog
      open={isOpen}
      onClose={handle}
      PaperProps={{
        component: 'form',
        onSubmit: onSubmit,
      }}
    >
```

2024-07-22 13:10 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +        onSubmit: (event: React.FormEvent<HTMLFormElement>) => {
остальное по образу и подобию, не буду их отдельно отмечать

2024-07-22 13:13 UTC, frontandrew reviewed
Хорошо. Форму выбора изображения для аватва можно было вынести в отдельную фичу, как и форму смены пароля. На текущем этапе этого достаточно.

И с отступами в карточке профиля я не понял как ты решил, мне кажется отступы меньше стали.

![image](https://github.com/user-attachments/assets/590b226e-99ad-4988-8da9-5ef0720edc1c)

А вот в твоей задаче:

<img width="1280" alt="msedge_x6g7Et3iRw" src="https://github.com/user-attachments/assets/1c8d63ce-72bb-4e83-8a6f-2474bc1aacc2">

Если это ок, напиши что это ок, я приму пиар.

2024-07-23 05:46 UTC, Ratanov reviewed
Прошу и в остальных файлах поправить замечания

2024-07-23 05:46 UTC, Ratanov commented on packages/client/src/pages/settings/components/card-user/view.tsx
>  export const CardUser: FC = () => {
**React.FC**
`export const CardUser: React.FC = () => {`

2024-07-23 05:46 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +type Password = Record<string, string>
Мне так нравится больше, ведь мы сразу видим названия типов
`type Password = {
  currentPassword: string;
  password: string;
  confirmPassword: string;
}`
Теперь она более конкретная, что улучшает типобезопасность

2024-07-23 05:46 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +  const [error, setError] = useState(false)
Ты завел два стейта с примитивами для одной фичи. Но ведь у нас есть сложная структура, такая как объект, для хранения стейта
`const [errorState, setErrorState] = useState({ text: 'Change password', error: false })`
На самом деле я против добавлять в переменные для стейта окончания State, но, возможно, тебе в объекте нужно именно название переменной **error** для ошибки. Если не обязательно, то лучше написать так
`const [error, setError] = useState({ text: 'Change password', isError: false })`
Далее код написан для **errorState** и **setErrorState**

2024-07-23 05:46 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +  const { form, handleSubmit } = useForm(formConfig)
Давай стараться как то единообразно стараться писать код. Где-то видел, что в useForm мы передаем объект, а не formConfig (сори, не заметил в прошлом пр). Что я имею ввиду:
Вместо `const { form, handleSubmit } = useForm(formConfig)` мы пишем 
```
const { form, handleSubmit } = useForm({
    onSubmit,
    validateOnBlur: true,
  })
```
Тут мы сразу видим, что хук useForm использует, а логику **onSubmit** распишем отдельно.

2024-07-23 05:46 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +  const onSubmit = (event: React.FormEvent<HTMLFormElement>) => {
нужно обернуть в **useCallback**, ведь **onSubmit** у нас может не меняться
```
const onSubmit = useCallback((formValues: Password) => {
    const result = validatePasswords(formValues)
    setErrorState(result)
  }, [validatePasswords])
```

2024-07-23 05:46 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +    onSubmit: (formValues: Password) => {
вынесем логику валидации паролей в отдельную функцию **validatePasswords**, а также будем использовать **useCallback** для мемоизации функций, чтобы избежать ненужных ререндеров.
Так как мы объединили состояния ошибки, сразу перепишем весь код
```
const validatePasswords = useCallback((values: Password) => {
    if (values.currentPassword === values.password) {
      return { error: true, text: 'Do not repeat the current password' }
    }
    if (values.password !== values.confirmPassword) {
      return { error: true, text: 'Passwords do not match' }
    }
    return { error: false, text: 'Password changed successfully' }
  }, [])
```
Как видишь, мы избавились от 3го if, просто возвращая результат с помощью return (код после return не возвращается). Код стал чище и улучшилась читаемость

2024-07-23 05:46 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +        console.log('work')
косяк с консоль логом

2024-07-23 05:46 UTC, Ratanov commented on packages/client/src/pages/settings/components/form-user/components/change-password/view.tsx
> +        <FieldText
Ага мы видим, что код повторяется. А почему бы не написать цикл?
```
{['currentPassword', 'password', 'confirmPassword'].map((elem) => (
          <FieldText
            key={elem}
            form={form}
            name={elem}
            label={elem === 'currentPassword' ? 'Current password' : elem === 'password' ? 'New password' : 'Confirm new password'}
            type="password"
            validator={validators.password}
            size="small"
            required
          />
        ))}
```

2024-07-26 15:32 UTC, Ratanov approved these changes

2024-08-04 13:02 UTC, closed without merging